[package]
name = "serializable_log_record"
version = "0.3.2"
edition = "2018"
description = "Convert a log::Record to a serializable format. Not as straightforward as it sounds, because the log::Record contains a non-serializable type. This crate provides a way to deal with situation."
repository = "https://github.com/8192K/serializable_log_record"
authors = ["Sebastian Frehmel <8192K@sebastianfrehmel.de>"]
license = "MIT/Apache-2.0"
categories = ["development-tools", "development-tools::debugging", "encoding"]
keywords = ["log", "logger", "logging", "serialize", "record"]
readme = "README.md"

[dependencies]
log = "0.4"
serde = { version = "1.0", default-features = false, features = [
  "derive",
], optional = true }
bincode = { version = "2.0.0-rc", default-features = false, optional = true }

[features]
serde = ["dep:serde"]
bincode2 = ["dep:bincode"]

[profile.release]
lto = true
codegen-units = 1

